import type { AchievementDefinition, AchievementFamily } from '../types';

export const FAMILY_LABELS: Record<AchievementFamily, string> = {
  starter: 'Starter Keepsakes',
  meals: 'Meals',
  rhythm: 'Rhythm',
  photographs: 'Photographs',
  notes: 'Notes',
  feelings: 'Feelings',
  people: 'People',
  rare: 'Rare Moments',
  monthly: 'Monthly Keepsakes',
  seasonal: 'Seasonal Keepsakes',
};

export const FAMILY_ORDER: AchievementFamily[] = [
  'meals',
  'rhythm',
  'people',
  'photographs',
  'feelings',
  'notes',
  'rare',
  'monthly',
  'seasonal',
];

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  {
    id: 'first-plate',
    family: 'starter',
    tier: 1,
    title: 'First Plate',
    description: 'The first meal found its place at the table.',
    iconKey: 'plate-small',
    ruleType: 'meal_count',
    threshold: 1,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 10,
  },
  {
    id: 'feeling-candle',
    family: 'starter',
    tier: 1,
    title: 'Feeling Candle',
    description: 'A feeling was named and left a little light behind.',
    iconKey: 'feeling-candle',
    ruleType: 'feeling_count',
    threshold: 1,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 20,
  },
  {
    id: 'pulled-chair',
    family: 'starter',
    tier: 1,
    title: 'Pulled Chair',
    description: 'A real person profile took a seat at one meal.',
    iconKey: 'people-pulled-chair',
    ruleType: 'shared_meal_count',
    threshold: 1,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 30,
  },
  {
    id: 'little-photograph',
    family: 'starter',
    tier: 1,
    title: 'Little Photograph',
    description: 'A meal became visible enough to keep as an image.',
    iconKey: 'photo-single',
    ruleType: 'meal_photo_count',
    threshold: 1,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 40,
  },
  {
    id: 'written-corner',
    family: 'starter',
    tier: 1,
    title: 'Written Corner',
    description: 'A note stayed after the meal was over.',
    iconKey: 'note-corner',
    ruleType: 'note_count',
    threshold: 1,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 50,
  },

  {
    id: 'small-tablecloth',
    family: 'meals',
    tier: 1,
    title: 'Small Tablecloth',
    description: 'Three meals began to make the table feel lived in.',
    iconKey: 'meal-tablecloth-small',
    ruleType: 'meal_count',
    threshold: 3,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 110,
  },
  {
    id: 'set-table',
    family: 'meals',
    tier: 2,
    title: 'Set Table',
    description: 'Ten meals now sit together like a small chapter.',
    iconKey: 'meal-set-table',
    ruleType: 'meal_count',
    threshold: 10,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 120,
  },
  {
    id: 'well-loved-table',
    family: 'meals',
    tier: 3,
    title: 'Well-Loved Table',
    description: 'Thirty meals have left their gentle marks.',
    iconKey: 'meal-well-loved',
    ruleType: 'meal_count',
    threshold: 30,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 130,
  },
  {
    id: 'long-table',
    family: 'meals',
    tier: 4,
    title: 'Long Table',
    description: 'One hundred meals stretch into a long table of days.',
    iconKey: 'meal-long-table',
    ruleType: 'meal_count',
    threshold: 100,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 140,
  },
  {
    id: 'table-of-seasons',
    family: 'meals',
    tier: 5,
    title: 'Table of Seasons',
    description: 'Two hundred and fifty meals carry the table through seasons.',
    iconKey: 'meal-seasons-table',
    ruleType: 'meal_count',
    threshold: 250,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 150,
  },
  {
    id: 'life-at-the-table',
    family: 'meals',
    tier: 6,
    title: 'A Life at the Table',
    description: 'Five hundred meals become a living archive.',
    iconKey: 'meal-life-table',
    ruleType: 'meal_count',
    threshold: 500,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 160,
  },

  {
    id: 'three-quiet-days',
    family: 'rhythm',
    tier: 1,
    title: 'Three Quiet Days',
    description: 'Meals appeared across three different days.',
    iconKey: 'rhythm-three-days',
    ruleType: 'distinct_days',
    threshold: 3,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 210,
  },
  {
    id: 'seven-quiet-days',
    family: 'rhythm',
    tier: 2,
    title: 'Seven Quiet Days',
    description: 'A gentle stretch of seven meal days gathered.',
    iconKey: 'rhythm-seven-days',
    ruleType: 'distinct_days',
    threshold: 7,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 220,
  },
  {
    id: 'month-remembered',
    family: 'rhythm',
    tier: 3,
    title: 'A Month Remembered',
    description: 'One month held meals on fifteen different days.',
    iconKey: 'rhythm-month-page',
    ruleType: 'monthly_distinct_days',
    threshold: 15,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 230,
  },
  {
    id: 'gentle-rhythm',
    family: 'rhythm',
    tier: 4,
    title: 'Gentle Rhythm',
    description: 'Three months in a row each held at least one meal.',
    iconKey: 'rhythm-three-months',
    ruleType: 'monthly_presence_streak',
    threshold: 3,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 240,
  },
  {
    id: 'four-seasons',
    family: 'rhythm',
    tier: 5,
    title: 'Four Seasons',
    description: 'Meals were remembered in spring, summer, autumn, and winter.',
    iconKey: 'rhythm-four-seasons',
    ruleType: 'season_coverage',
    threshold: 4,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 250,
  },
  {
    id: 'year-at-the-table',
    family: 'rhythm',
    tier: 6,
    title: 'Year at the Table',
    description: 'Twelve months in a row each held at least one meal.',
    iconKey: 'rhythm-year-table',
    ruleType: 'monthly_presence_streak',
    threshold: 12,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 260,
  },

  {
    id: 'photo-strip',
    family: 'photographs',
    tier: 2,
    title: 'Photo Strip',
    description: 'Five photographs began a visible thread of meals.',
    iconKey: 'photo-strip',
    ruleType: 'photo_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 310,
  },
  {
    id: 'table-album',
    family: 'photographs',
    tier: 3,
    title: 'Table Album',
    description: 'Fifteen photographs made a small album.',
    iconKey: 'photo-album',
    ruleType: 'photo_count',
    threshold: 15,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 320,
  },
  {
    id: 'memory-box',
    family: 'photographs',
    tier: 4,
    title: 'Memory Box',
    description: 'Fifty photographs are tucked away for later.',
    iconKey: 'photo-memory-box',
    ruleType: 'photo_count',
    threshold: 50,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 330,
  },
  {
    id: 'family-album',
    family: 'photographs',
    tier: 5,
    title: 'Family Album',
    description: 'One hundred photographs became a generous album.',
    iconKey: 'photo-family-album',
    ruleType: 'photo_count',
    threshold: 100,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 340,
  },

  {
    id: 'margin-notes',
    family: 'notes',
    tier: 2,
    title: 'Margin Notes',
    description: 'Five meals carried a note in the margin.',
    iconKey: 'note-margins',
    ruleType: 'note_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 410,
  },
  {
    id: 'table-journal',
    family: 'notes',
    tier: 3,
    title: 'Table Journal',
    description: 'Fifteen meal notes now read like a table journal.',
    iconKey: 'note-journal',
    ruleType: 'note_count',
    threshold: 15,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 420,
  },
  {
    id: 'worn-notebook',
    family: 'notes',
    tier: 4,
    title: 'Worn Notebook',
    description: 'Forty meal notes have softened the notebook edges.',
    iconKey: 'note-worn-book',
    ruleType: 'note_count',
    threshold: 40,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 430,
  },
  {
    id: 'book-of-meals',
    family: 'notes',
    tier: 5,
    title: 'Book of Meals',
    description: 'One hundred meal notes became a quiet book.',
    iconKey: 'note-book-meals',
    ruleType: 'note_count',
    threshold: 100,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 440,
  },

  {
    id: 'mood-vase',
    family: 'feelings',
    tier: 2,
    title: 'Mood Vase',
    description: 'Five meals carried their own emotional weather.',
    iconKey: 'feeling-vase',
    ruleType: 'feeling_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 510,
  },
  {
    id: 'full-bouquet',
    family: 'feelings',
    tier: 3,
    title: 'Full Bouquet',
    description: 'Fifteen feelings gathered like stems in a vase.',
    iconKey: 'feeling-bouquet',
    ruleType: 'feeling_count',
    threshold: 15,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 520,
  },
  {
    id: 'mood-lantern',
    family: 'feelings',
    tier: 4,
    title: 'Mood Lantern',
    description: 'Forty meals were lit by named feelings.',
    iconKey: 'feeling-lantern',
    ruleType: 'feeling_count',
    threshold: 40,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 530,
  },
  {
    id: 'emotional-almanac',
    family: 'feelings',
    tier: 5,
    title: 'Emotional Almanac',
    description: 'One hundred feelings make a small emotional almanac.',
    iconKey: 'feeling-almanac',
    ruleType: 'feeling_count',
    threshold: 100,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 540,
  },

  {
    id: 'familiar-seat',
    family: 'people',
    tier: 1,
    title: 'Familiar Seat',
    description: 'One person returned to the table three times.',
    iconKey: 'people-cushion-chair',
    ruleType: 'same_person_meals',
    threshold: 3,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 610,
  },
  {
    id: 'regular-at-my-table',
    family: 'people',
    tier: 2,
    title: 'Regular at My Table',
    description: 'One person shared ten meals with you.',
    iconKey: 'people-regular-seat',
    ruleType: 'same_person_meals',
    threshold: 10,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 620,
  },
  {
    id: 'old-friends-place',
    family: 'people',
    tier: 3,
    title: "Old Friend's Place",
    description: 'One person has appeared in twenty-five meal memories.',
    iconKey: 'people-old-friend-seat',
    ruleType: 'same_person_meals',
    threshold: 25,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 630,
  },
  {
    id: 'table-company',
    family: 'people',
    tier: 1,
    title: 'Table Company',
    description: 'Five shared meals remembered who was there.',
    iconKey: 'people-two-seats',
    ruleType: 'shared_meal_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 640,
  },
  {
    id: 'open-table',
    family: 'people',
    tier: 2,
    title: 'Open Table',
    description: 'Five different people have taken a seat.',
    iconKey: 'people-open-table',
    ruleType: 'unique_people_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 650,
  },
  {
    id: 'many-seats',
    family: 'people',
    tier: 3,
    title: 'Many Seats',
    description: 'Ten different people are part of your table archive.',
    iconKey: 'people-many-seats',
    ruleType: 'unique_people_count',
    threshold: 10,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 660,
  },
  {
    id: 'full-table',
    family: 'people',
    tier: 2,
    title: 'Full Table',
    description: 'Three or more people gathered around one meal.',
    iconKey: 'people-full-table',
    ruleType: 'single_meal_people_count',
    threshold: 3,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 670,
  },
  {
    id: 'house-full',
    family: 'people',
    tier: 3,
    title: 'House Full',
    description: 'Five people shared one generous table.',
    iconKey: 'people-house-full',
    ruleType: 'single_meal_people_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 680,
  },
  {
    id: 'shared-photograph',
    family: 'people',
    tier: 1,
    title: 'Shared Photograph',
    description: 'A photograph remembered being together.',
    iconKey: 'people-polaroid-two',
    ruleType: 'shared_photo_count',
    threshold: 1,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 690,
  },
  {
    id: 'photo-together',
    family: 'people',
    tier: 2,
    title: 'Photo Together',
    description: 'Five shared photographs now sit near the table.',
    iconKey: 'people-photo-together',
    ruleType: 'shared_photo_count',
    threshold: 5,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 700,
  },
  {
    id: 'table-reunion',
    family: 'people',
    tier: 3,
    title: 'Table Reunion',
    description: 'A familiar person returned after at least sixty days.',
    iconKey: 'people-reunion-ring',
    ruleType: 'table_reunion',
    threshold: 60,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 710,
  },
  {
    id: 'same-table-new-season',
    family: 'people',
    tier: 4,
    title: 'Same Table, New Season',
    description: 'One person shared meals with you in two different seasons.',
    iconKey: 'people-season-seats',
    ruleType: 'same_person_season_count',
    threshold: 2,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 720,
  },

  {
    id: 'midnight-plate',
    family: 'rare',
    tier: 1,
    title: 'Midnight Plate',
    description: 'A meal was remembered after 11 PM.',
    iconKey: 'rare-midnight-plate',
    ruleType: 'late_meal_count',
    threshold: 1,
    hidden: true,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 810,
  },
  {
    id: 'sunday-table',
    family: 'rare',
    tier: 1,
    title: 'Sunday Table',
    description: 'Four different Sundays held a meal memory.',
    iconKey: 'rare-sunday-table',
    ruleType: 'weekday_meal_days',
    threshold: 4,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 820,
  },
  {
    id: 'breakfast-sun',
    family: 'rare',
    tier: 1,
    title: 'Breakfast Sun',
    description: 'Ten breakfasts caught the morning light.',
    iconKey: 'rare-breakfast-sun',
    ruleType: 'meal_type_count',
    threshold: 10,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 830,
  },
  {
    id: 'sweet-corner',
    family: 'rare',
    tier: 1,
    title: 'Sweet Corner',
    description: 'Ten treats found their small corner.',
    iconKey: 'rare-sweet-corner',
    ruleType: 'meal_type_count',
    threshold: 10,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 840,
  },
  {
    id: 'complete-memory',
    family: 'rare',
    tier: 2,
    title: 'A Complete Memory',
    description: 'One meal held feeling, company, photo, and note together.',
    iconKey: 'rare-complete-memory',
    ruleType: 'complete_memory',
    threshold: 1,
    active: true,
    celebrationLevel: 'major',
    sortOrder: 850,
  },
  {
    id: 'dinner-by-candlelight',
    family: 'rare',
    tier: 2,
    title: 'Dinner by Candlelight',
    description: 'A dinner held feeling, company, and photograph.',
    iconKey: 'rare-candle-dinner',
    ruleType: 'dinner_complete',
    threshold: 1,
    hidden: true,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 860,
  },
  {
    id: 'first-of-the-year',
    family: 'rare',
    tier: 1,
    title: 'First of the Year',
    description: 'A year opened with a first meal memory.',
    iconKey: 'rare-first-year',
    ruleType: 'year_boundary',
    threshold: 1,
    active: true,
    celebrationLevel: 'quiet',
    sortOrder: 870,
  },
  {
    id: 'last-plate-of-the-year',
    family: 'rare',
    tier: 1,
    title: 'Last Plate of the Year',
    description: 'The year closed with one last plate.',
    iconKey: 'rare-last-year',
    ruleType: 'year_boundary',
    threshold: 1,
    hidden: true,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 880,
  },
  {
    id: 'birthday-table',
    family: 'rare',
    tier: 2,
    title: 'Birthday Table',
    description: 'A celebratory shared meal made a small ceremony.',
    iconKey: 'rare-birthday-table',
    ruleType: 'celebration_shared_meal',
    threshold: 1,
    hidden: true,
    active: true,
    celebrationLevel: 'standard',
    sortOrder: 890,
  },

  {
    id: 'monthly-letter',
    family: 'monthly',
    tier: 1,
    title: 'Monthly Letter',
    description: 'A monthly keepsake placeholder for future rituals.',
    iconKey: 'monthly-letter',
    ruleType: 'manual',
    threshold: 1,
    active: false,
    seasonal: false,
    celebrationLevel: 'quiet',
    sortOrder: 910,
  },
  {
    id: 'seasonal-table-stamp',
    family: 'seasonal',
    tier: 1,
    title: 'Seasonal Table Stamp',
    description: 'A seasonal keepsake placeholder for future tables.',
    iconKey: 'seasonal-table-stamp',
    ruleType: 'manual',
    threshold: 1,
    active: false,
    seasonal: true,
    celebrationLevel: 'quiet',
    sortOrder: 920,
  },
];
