const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename);
const { effectiveMemory, memoryState, inferMealType, periodRange, recordedComparison, normalizedName } = require('../src/product/memory.ts');
const { photoDate } = require('../src/product/exif.ts');
const { validateInput, validateNarrative } = require('../src/insights/contract.ts');
const meal = { id: 'a', date: '2026-09-30', time: '12:00', title: 'Coffee', mealType: 'snack', photoUri: 'blob:test', moodTags: [], peopleTags: [], personIds: [] };
assert.equal(effectiveMemory(meal), false);
assert.equal(memoryState(meal), 'minimal');
assert.equal(effectiveMemory({ ...meal, peopleTags: ['just-me'] }), true);
assert.equal(memoryState({ ...meal, archivedAt: 'now' }), 'archived');
assert.equal(inferMealType('08:00'), 'breakfast'); assert.equal(inferMealType('19:00'), 'dinner'); assert.equal(inferMealType('15:00'), 'snack');
assert.deepEqual(periodRange('2026-10-01', 'week'), { start: '2026-09-28', end: '2026-10-04' });
assert.deepEqual(periodRange('2024-02-20', 'month'), { start: '2024-02-01', end: '2024-02-29' });
assert.throws(() => periodRange('2026-02-30', 'month'));
assert.equal(recordedComparison([meal], []).soloShare, null);
assert.equal(normalizedName(' MOM '), normalizedName('mom'));
assert.equal(photoDate(new ArrayBuffer(1)), undefined);
const bytes = new ArrayBuffer(100), v = new DataView(bytes);
v.setUint16(0, 0xffd8); v.setUint16(2, 0xffe1); v.setUint16(4, 94); v.setUint32(6, 0x45786966); v.setUint16(10, 0); v.setUint16(12, 0x4949); v.setUint16(14, 42, true); v.setUint32(16, 8, true);
v.setUint16(20, 1, true); v.setUint16(22, 0x9003, true); v.setUint16(24, 2, true); v.setUint32(26, 20, true); v.setUint32(30, 30, true);
new Uint8Array(bytes, 42, 20).set(new TextEncoder().encode('2026:09:30 19:20:00\0'));
assert.deepEqual(photoDate(bytes), { date: '2026-09-30', time: '19:20' });
new Uint8Array(bytes, 42, 20).set(new TextEncoder().encode('2026:02:30 19:20:00\0')); assert.equal(photoDate(bytes), undefined);
const input = { version: 1, month: '2026-09', locale: 'en', period: 'week', rangeStart: '2026-09-28', rangeEnd: '2026-10-04', meals: [{ id: 'a', date: '2026-10-01', title: 'Coffee', mealType: 'snack', moodTags: [], companyTags: [], note: '', hasPhoto: true }] };
assert.equal(validateInput(input).meals[0].date, '2026-10-01');
assert.throws(() => validateInput({ ...input, rangeEnd: '2026-10-30' }));
assert.throws(() => validateInput({ ...input, meals: [{ ...input.meals[0], date: '2026-10-05' }] }));
assert.throws(() => validateNarrative({ title: 'bad', observations: [{ text: 'fake', mealIds: ['not-provided'] }] }, ['a']));
console.log('PASS product: effective memories, sparse comparison, periods, EXIF bounds and reference redline');
