export const DEMO_MEAL_PHOTOS = {
  berryToast: require('../../assets/demo/meal-photos/berry-toast.jpg'),
  blueberryToast: require('../../assets/demo/meal-photos/blueberry-toast.jpg'),
  cafePastaSpread: require('../../assets/demo/meal-photos/cafe-pasta-spread.jpg'),
  cafeTiramisuDrinks: require('../../assets/demo/meal-photos/cafe-tiramisu-drinks.jpg'),
  counterDessert: require('../../assets/demo/meal-photos/counter-dessert.jpg'),
  creamToast: require('../../assets/demo/meal-photos/cream-toast.jpg'),
  eveningDrinks: require('../../assets/demo/meal-photos/evening-drinks.jpg'),
  fruitGranolaBowl: require('../../assets/demo/meal-photos/fruit-granola-bowl.jpg'),
  homeStew: require('../../assets/demo/meal-photos/home-stew.jpg'),
  mangoStickyRice: require('../../assets/demo/meal-photos/mango-sticky-rice.jpg'),
  pastaBowl: require('../../assets/demo/meal-photos/pasta-bowl.jpg'),
  riceBowl: require('../../assets/demo/meal-photos/rice-bowl.jpg'),
  saladWindowTable: require('../../assets/demo/meal-photos/salad-window-table.jpg'),
  salmonAvocadoBowl: require('../../assets/demo/meal-photos/salmon-avocado-bowl.jpg'),
  seasonalSalad: require('../../assets/demo/meal-photos/seasonal-salad.jpg'),
  sharedHotpot: require('../../assets/demo/meal-photos/shared-hotpot.jpg'),
  sharedTableSpread: require('../../assets/demo/meal-photos/shared-table-spread.jpg'),
  smallPlatedBites: require('../../assets/demo/meal-photos/small-plated-bites.jpg'),
  sushiSet: require('../../assets/demo/meal-photos/sushi-set.jpg'),
  sushiHandRolls: require('../../assets/demo/meal-photos/sushi-hand-rolls.jpg'),
  tableFeast: require('../../assets/demo/meal-photos/table-feast.jpg'),
} as const;
